### ISSUE TITLE
🤢 Activity Bar Badge doesn't show smoothly.

### ISSUE THREAD

**Issue by afozbek** [yedhrab/DarkCode-Theme#2]
Hi, thanks for writing this extension. I was using Dark Code before I saw this color theme. Thank you for that.

But activity bar badge is not shown very clearly. You can look at following image

<img width="1027" alt="Screen Shot 2019-12-12 at 21 46 11" src="https://user-images.githubusercontent.com/37661157/70739911-f7b5b700-1d28-11ea-8030-46ee8ad53318.png">

**Comment by yemreak** [comment]
I have just fixed it 🚀

![image](https://user-images.githubusercontent.com/49655146/70742086-d3a8a480-1d2d-11ea-9ec2-4ce0a9c72c93.png)

**Comment by afozbek** [comment]
Thank you
