### ISSUE TITLE
🚧 The activity bar is intertwined with the editor

### ISSUE THREAD

**Issue by asmaamirkhan** [yedhrab/DarkCode-Theme#3]
Hi,

I suggest you to make the activity bar border more salient with some smooth color to separate it from the editor for better UI.

⭐ As an example:
![image](https://user-images.githubusercontent.com/45575570/71318573-80f48880-24a3-11ea-8343-923dcca465b1.png)

> Thanks for the great theme 😊

**Comment by yemreak** [comment]
Will be added to new release, thank you for your suggestion 😊
