### ISSUE TITLE
🐞 Updated Extension today displayed: "Couldn't parse the Changelog"

### ISSUE THREAD

**Issue by ghost** [yedhrab/DarkCode-Theme#6]
Hey @yedhrab ! 😊👋🏼

Congratulations on your great extension !

With this i can help you :
``` Typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  vscode.commands.executeCommand('markdown.api.render', '# Hello Markdown').then(result => {
    console.log(`rendered markdown: ${result}`);
  });
}
```
I think you use the webview api, so it can accept the rendered html as input.
When you'll have time give it a try.😉
Best !

**Comment by yemreak** [comment]
🙋‍♂️ Hi @Denis-net 

Thank you for congratulation. I retyped my `Changelog.md` files, now it appears ✨ well (and 📝 detailed). Also, thank you for markdown -> html api. I didn't use it but it doesn't mean that I won't use 💁‍♂️.

![image](https://user-images.githubusercontent.com/49655146/73256415-e76f7380-41d2-11ea-967c-1391d9e6dc36.png)

Regards
